name: Build and Publish Release

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Mingw64
      run: |
        choco install -y mingw
        choco install -y windows-sdk-10-version-1903-all
        choco install -y visualstudio2019community

    - name: Build with make
      run: |
        mingw32-make

    - name: Create Release
      id: create_release
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0-${{ github.sha }}
        release_name: Release v1.0-${{ github.sha }}
        body: |
          Release created automatically by GitHub Actions.
        draft: true
        prerelease: false

    - name: Upload release asset
      if: success()
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./batch.exe
        asset_name: batch.exe
        asset_content_type: application/octet-stream
