name: Build and Publish Release

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install mingw64
      run: |
        choco install -y mingw

    - name: Build with make
      run: |
        mingw32-make

    - name: Publish release
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        body: |
          Release created automatically by GitHub Actions.
        draft: false
        prerelease: false
        files: |
          batch.exe
